### ISSUE TITLE
Busca case-insentive ou não?  (em python)

### ISSUE THREAD

**Issue by alsombra** [arademaker/ED-2017-2#18]
Estou abrindo essa issue para discussão sobre a implementação da busca a partir da trie do @matheusbortolini.

Estou construindo a função que vai fazer a query e percebi que a Trie que é gerada no get_trie.py é **uma árvore de palavras todas em lower case**. Seria melhor eu modificar para fazer a Trie com as palavras como vem da lista de entidades (case-sensitive) e fazer uma busca case-sensitive assim ou fazer uma busca em lower case msm? (passando todas as sentenças pra lower case). 

Fazendo tudo em lower case seria uma busca mais abrangente e poderíamos pegar sentenças que tivessem entidades erradamente escritas com minúsculas, mas talvez poderíamos pegar casos indesejados.

**Comment by arademaker** [comment]
Acho que toda esta discussão de case é detalhe, refinamento para depois que a estrutura do código estiver pronta.

**Comment by alsombra** [comment]
Ok, professor. Foi feito case-insensitive. Deixarei uma outra issue aberta para fazermos sugestões para discussões e melhoras futuras.
